package com.poketrirx.marble.teamservice.teams.pub.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.google.common.collect.ImmutableList;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.Singular;
import lombok.ToString;

/**
 * A POJO representing a Team resource.
 */
@DynamoDBTable(tableName = "Team")
@ToString
@EqualsAndHashCode
@AllArgsConstructor(access = AccessLevel.PROTECTED)
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Builder(toBuilder = true)
public final class Team {
    /**
     * The unique identifier of the team resource.
     */
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Builder.Default
    @NonNull
    @Getter
    private final String id = "";

    /**
     * The unique identifier of the related user resource.
     */
    @DynamoDBAttribute
    @Builder.Default
    @NonNull
    @Getter
    private final String userId = "";

    /**
     * The unique identifier of the related league resource.
     */
    @DynamoDBAttribute
    @Builder.Default
    @NonNull
    @Getter
    private final String leagueId = "";

    /**
     * The name of the team.
     */
    @DynamoDBAttribute
    @Builder.Default
    @NonNull
    @Getter
    private final String name = "";

    /**
     * The home city of the team.
     */
    @DynamoDBAttribute
    @Builder.Default
    @NonNull
    @Getter
    private final String city = "";

    /**
     * The bio for the team.
     */
    @DynamoDBAttribute
    @Builder.Default
    @NonNull
    @Getter
    private final String bio = "";

    /**
     * An absolute url that points to a profile image for the team.
     */
    @DynamoDBAttribute
    @Builder.Default
    @NonNull
    @Getter
    private final String profileImage = "";

    /**
     * An absolute url that points to a profile image for the team.
     */
    @DynamoDBAttribute
    @NonNull
    @Getter
    @Singular
    private ImmutableList<Assignment> assignments;
}